package myClient;

public enum Commands {
	C_CREATE_PERSON,
	C_CANCEL_CREATE_PERSON,
	ADD_RELATION_FAMILY,
	C_MENU_SHOW_CREATE_PERSON_PANEL, 
	C_MENU_SHOW_SEARCH_RELATION_FAMILY_PANEL,
	C_LOGIN_BUTTON_ENTRY, 
	C_LOGIN_BUTTON_REGISTRY, 
	C_LOGIN_BUTTON_RECOVER_PASSWORD,
	C_MENU_SEARCH_RELATIONS_FAMILIES;
}
