package myClient;
/**
 * comandos para los eventos que se manejan en el Cliente
 * @author Grupo 2 -- Darwin Vargas --Andres Amezquita Gordillo-- Andres Felipe Moreno
 *
 */
public enum Commands {
	C_CREATE_PERSON,
	C_CANCEL_CREATE_PERSON,
	ADD_RELATION_FAMILY,
	C_MENU_SHOW_CREATE_PERSON_PANEL, 
	C_MENU_SHOW_SEARCH_RELATION_FAMILY_PANEL,
	C_LOGIN_BUTTON_ENTRY, 
	C_MENU_CREATE_RELATION_FAMILY,
	C_LOGIN_BUTTON_REGISTRY, 
	C_LOGIN_BUTTON_RECOVER_PASSWORD,
	C_MENU_SEARCH_RELATIONS_FAMILIES,
	EXIT,
	BEFORE, 
	AFTER, 
	AUX, 
	ADD_RELATION_FAMILY_2, 
	C_MENU_SET_DATAS,
	C_BUTTON_SET_DATAS;
}
