package myClient;

public enum Commands {
	C_CREATE_PERSON,ADD_RELATION_FAMILY, C_MENU_SHOW_CREATE_PERSON_PANEL, PANEL_TWO,
	C_LOGIN_ENTRY, C_LOGIN_REGISTRY, C_LOGIN_RECOVER_PASSWORD,PANEL_ONE, SEARCH_RELATIONS_FAMILIES;
}
